site_name: My Docs
theme:
  name: material
  font: 
    text: Space Grotesk
  logo: assets/lb2c.png
  favicon: assets/lb2c.png
  features:
    - navigation.footer
  palette:
   # primary: deep purple
    # Palette toggle for light mode
    - primary: deep purple
      accent : deep orange
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      accent : deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

#Code to add emojis/icons
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
 
  #Code to make code text stand out
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  
  #Content tabs : use === to make new tabs
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

copyright: Copyright &copy; 2025 LeValle Bradix

