site_name: Docs by LB
site_url: https://docs.bradix.org
use_directory_urls: true
theme:
  name: material
  custom_dir: overrides
  font: 
    text: Space Grotesk
  logo: assets/lb2c.png
  favicon: assets/lb2c.png
  features:
    - navigation.top
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
    - content.tabs.link
  extra_css:
  - assets/stylesheets/custom.css

  palette:
   # primary: deep purple
    # Palette toggle for light mode
    - primary: deep purple
      accent : deep orange
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      accent : deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
   - search
   - awesome-nav
      

#Code to add emojis/icons
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
 
  #Code to make code text stand out
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  
  #Content tabs : use === to make new tabs

  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  
  - pymdownx.mark:

  #Adding admonition
  - admonition
  - pymdownx.details
  - pymdownx.superfences   

copyright: Copyright &copy; 2025 LeValle Bradix

